name: Dev
variables:
  - secret: true
    name: MY_TELEGRAM_BOT
  - secret: true
    name: TELEGRAM_WEBHOOK_SECRET
  - secret: false
    name: TELEGRAM_CHAT_ID
  - secret: false
    name: TELEGRAM_WEBHOOK_URL
